### ISSUE TITLE
I can't log in to the Admin Panel

### ISSUE THREAD

**Issue by VlaK0r** [Rabbit-Company/Passky-Server#47]
Hello!
Thank you for your program.

I enter the account details, press enter and nothing happens.

**Comment by zigazajc007** [comment]
Hello,

Can you try to shutdown your Passky server with:
```bash
docker-compose down
```
and start it again with:
```bash
docker-compose up -d
```

**Comment by VlaK0r** [comment]
I did this, it didn't help

**Comment by VlaK0r** [comment]
The server itself is working and I can go to its page. But I can't log in to the admin panel.

**Comment by zigazajc007** [comment]
Do you see any errors if you execute?
```
docker logs passky-server
```

**Comment by VlaK0r** [comment]
> Do you see any errors if you execute?
> 
> ```
> docker logs passky-server
> ```

Linux; Android 13; SM-A525F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobil
e Safari/537.36"
127.0.0.1 - - [24/Jul/2023:17:51:01 +0000] "GET /cron.php HTTP/1.1" 200 31 "-" "curl/7.81.
0"
5.142.42.106 - - [24/Jul/2023:17:51:05 +0000] "POST /website/actions/login.php HTTP/1.1" 3
02 5 "-" "Mozilla/5.0 (Linux; Android 13; SM-A525F) AppleWebKit/537.36 (KHTML, like Gecko)
 Chrome/114.0.0.0 Mobile Safari/537.36"
5.142.42.106 - - [24/Jul/2023:17:51:05 +0000] "GET / HTTP/1.1" 200 2413 "-" "Mozilla/5.0 (
Linux; Android 13; SM-A525F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobil
e Safari/537.36"

**Comment by VlaK0r** [comment]
What does it mean?

**Comment by zigazajc007** [comment]
Hello,

There aren't any errors here.

Can you contact me on a Discord: ziga.zajc007 or email: ziga.zajc007@gmail.com

We had similar issue before, so I have deployed a test VPS and let him deploy Passky Server on their own. But this time it worked for him. So he had an issue that I don't remember on his local network.

We can try this as well.

**Comment by NOXITB** [comment]
Their is an issue for non signed certs on the admin panel because it tries to verify https connection

**Comment by devneok** [comment]
Docker or Self hosting cannot connect to database, therefore you cannot login into Admin. 
Check database you will find nothing in there, I cannot connect to DB during install as well. network host I'm looking for a fix as well.

**Comment by eric2788** [comment]
I have created database and no connection error message in the log, still didn't auto create tables
using docker container too
when I login it said cannot connect to database

edit: and finally I can login after clear redis cache (admin panel still cannot, but browser extension i can

**Comment by zigazajc007** [comment]
> I have created database and no connection error message in the log, still didn't auto create tables using docker container too when I login it said cannot connect to database
> 
> edit: and finally I can login after clear redis cache (admin panel still cannot, but browser extension i can

Hello,

Can you check if username or password in your .env file contain any special characters that aren't correctly escaped?
